# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# name of the pipeline
name: CICD Pipeline

# Trigger condition for git repository and branch
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# jobs are used to run in an isolated environment
jobs:
  compile:
    # runs-on is used for the VM version supported by GitHub
    runs-on: ubuntu-latest

    steps:
      # uses are for already existing actions instead of writing commands
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4

        # with is used for providing the parameters based on the requirements below
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn compile

  # security-check is a job name used to run security scanning tools as part of the CI/CD pipeline.
  security-check:

    # runs-on is used for the VM version supported by GitHub
    runs-on: ubuntu-latest

    steps:
      # uses are for already existing actions instead of writing commands
      - uses: actions/checkout@v4

      - name: Trivy Installation

        # we used [ | pipe ] for running multiple commands in a single execution "run command"
        run: |
          sudo apt-get install wget gnupg -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update -y
          sudo apt-get install trivy -y

      # Trivy performs a File System (FS) scan to identify vulnerabilities,
      # misconfigurations, and security issues in the source code repository.
      - name: Trivy FS Scan
        run: trivy fs --format table -o fs-report.txt .

      # Gitleaks is installed to detect hardcoded secrets such as passwords,
      # API keys, tokens, and other sensitive information in the repository.
      - name: Gitleaks Installation
        run: sudo apt install gitleaks -y

      # Gitleaks scans the repository and generates a JSON report containing
      # any detected secrets or leaked credentials.
      - name: Gitleaks Code Scan
        run: gitleaks detect --source . -r gitleaks-report.json -f json
